//#############################################
//## file: MacrosParser.java
//## Generated by Byacc/j
//#############################################
package org.alberto.interprete.parsers.analizadormacros;

/**
 * BYACC/J Semantic Value for parser: MacrosParser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class MacrosParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public MacrosParserVal()
{
}
/**
 * Initialize me as an int
 */
public MacrosParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public MacrosParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public MacrosParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public MacrosParserVal(Object val)
{
  obj=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
